name: GitHub Actions for Nuxt.js

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 10.x

    steps:
      - uses: actions/checkout@master
      - uses: artmarydotir/nuxt-action@master
      - uses: actions/upload-artifact@master
        with:
          path: .nuxt
          name: artifact.zip
