name: GitHub Actions for Nuxt.js

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_VERSION: 10.x

    steps:
      - uses: actions/checkout@v1
      - uses: artmarydotir/nuxt-action@v0.1.0
      - uses: actions/upload-artifact@v1
        with:
          path: dist
          name: artifact.zip
